server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: ${APP_PATH:/}

logging:
  level:
    root: INFO

spring:
  neo4j:
    uri: bolt://${DB_HOST:localhost}:${DB_PORT:7687}
    authentication:
      username: ${DB_USER:neo4j}
      password: ${DB_PASS:test}
  security:
    cors:
      allowed-origins: "*"
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://localhost:8080/auth/realms/dev
          jwk-set-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/certs
  paging:
    page-size: 1000
