server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: ${APP_PATH:/}

logging:
  level:
    root: INFO

spring:
  neo4j:
    uri: bolt://${DB_HOST:localhost}:${DB_PORT:7687}
    authentication:
      username: ${DB_USER:neo4j}
      password: ${DB_PASS:test}
  security:
    cors:
      allowed-origins: "*"
    oauth2:
      enabled: ${OAUTH2_ENABLED:false}
      resourceserver:
        jwt:
          issuer-url: ${OAUTH2_URL:http://127.0.0.1:8081}/realms/${OAUTH2_REALM:top-realm}
          jwk-set-uri: ${OAUTH2_URL:http://127.0.0.1:8081}/realms/${OAUTH2_REALM:top-realm}/protocol/openid-connect/certs
  paging:
    page-size: 1000
