server:
  port: ${APP_PORT}
  servlet:
    context-path: ${APP_PATH}

spring:
  jooq:
    sql-dialect: Postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  security:
    cors:
      allowed-origins: "*"
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://localhost:8080/auth/realms/dev
          jwk-set-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/certs
