server:
  port: ${APP_PORT}
  servlet:
    context-path: ${APP_PATH}

logging:
  level:
    root: INFO

spring:
  neo4j:
    uri: bolt://${DB_HOST}:${DB_PORT}
    authentication:
      username: ${DB_USER}
      password: ${DB_PASS}
  security:
    cors:
      allowed-origins: "*"
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://localhost:8080/auth/realms/dev
          jwk-set-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/certs
  paging:
    page-size: 10